baseURL: "https://shao1116.github.io/website/" 
title: Jheng-Syuan Shao
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Education & Experiences
          url: Education_experience/
          weight: 1 
        - name: Publications
          url: Publications/
          weight: 2 
        - name: Awards & honors
          url: Awards_honors/
          weight: 3 
 #       - name: Books
 #         url: books/
 #         weight: 5 
 #       - name: Papers
 #         url: papers/
#          weight: 2
#        - name: Courses
#          url: courses/
#          weight: 3
#        - name: Data
#          url: data/
#          weight: 4 
#        - name: Blog
#          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
#          weight: 6

params:
    description: "This website hosts Moritz-Maria von Igelfeld's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Jheng-Syuan Shao
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jheng-Syuan Shao, Ph.D.
          subtitle: "Postdoctoral fellow at Institute of Biomedical Sciences, Academia Sinica  
          <br> Mucosal Immunology | Asthma"
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Education & Experiences
              url: Education_experience/
            - name: Publications
              url: Publications/
            - name: Awards & honors
              url: Awards_honors/
#            - name: Data
#              url: data/
#            - name: Books
#              url: books/
#            - name: Courses
#              url: courses/
#            - name: Tags
#              url: tags/
#            - name: Archive
#              url: archive/
#            - name: Blog
#              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:igelfeld@regensburg.edu
        - name: Zoom
          url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Substack
          url: https://pmichaillat.substack.com
        - name: YouTube
          url: https://www.youtube.com/@pmichaillat
        - name: Twitter
          url: https://x.com/pmichaillat
        - name: Bluesky
          url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jheng-Syuan Shao"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2